/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CategoryResource Provides information about a category and its ancestry. 
type CategoryResource struct {
	// The type of this resource: `categories`
	Type string `json:"type"`
	// The unique identifier for this category. This is a human-readable but URL-safe value. 
	Id string `json:"id"`
	Attributes CategoryResourceAttributes `json:"attributes"`
	Relationships CategoryResourceRelationships `json:"relationships"`
	Links *AccountResourceLinks `json:"links,omitempty"`
}

// NewCategoryResource instantiates a new CategoryResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryResource(type_ string, id string, attributes CategoryResourceAttributes, relationships CategoryResourceRelationships) *CategoryResource {
	this := CategoryResource{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewCategoryResourceWithDefaults instantiates a new CategoryResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryResourceWithDefaults() *CategoryResource {
	this := CategoryResource{}
	return &this
}

// GetType returns the Type field value
func (o *CategoryResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CategoryResource) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CategoryResource) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CategoryResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryResource) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryResource) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *CategoryResource) GetAttributes() CategoryResourceAttributes {
	if o == nil {
		var ret CategoryResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CategoryResource) GetAttributesOk() (*CategoryResourceAttributes, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CategoryResource) SetAttributes(v CategoryResourceAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *CategoryResource) GetRelationships() CategoryResourceRelationships {
	if o == nil {
		var ret CategoryResourceRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *CategoryResource) GetRelationshipsOk() (*CategoryResourceRelationships, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *CategoryResource) SetRelationships(v CategoryResourceRelationships) {
	o.Relationships = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CategoryResource) GetLinks() AccountResourceLinks {
	if o == nil || o.Links == nil {
		var ret AccountResourceLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryResource) GetLinksOk() (*AccountResourceLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CategoryResource) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given AccountResourceLinks and assigns it to the Links field.
func (o *CategoryResource) SetLinks(v AccountResourceLinks) {
	o.Links = &v
}

func (o CategoryResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	if true {
		toSerialize["relationships"] = o.Relationships
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableCategoryResource struct {
	value *CategoryResource
	isSet bool
}

func (v NullableCategoryResource) Get() *CategoryResource {
	return v.value
}

func (v *NullableCategoryResource) Set(val *CategoryResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryResource(val *CategoryResource) *NullableCategoryResource {
	return &NullableCategoryResource{value: val, isSet: true}
}

func (v NullableCategoryResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


