/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountResourceRelationshipsTransactionsLinks struct for AccountResourceRelationshipsTransactionsLinks
type AccountResourceRelationshipsTransactionsLinks struct {
	// The link to retrieve the related resource(s) in this relationship. 
	Related string `json:"related"`
}

// NewAccountResourceRelationshipsTransactionsLinks instantiates a new AccountResourceRelationshipsTransactionsLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResourceRelationshipsTransactionsLinks(related string) *AccountResourceRelationshipsTransactionsLinks {
	this := AccountResourceRelationshipsTransactionsLinks{}
	this.Related = related
	return &this
}

// NewAccountResourceRelationshipsTransactionsLinksWithDefaults instantiates a new AccountResourceRelationshipsTransactionsLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResourceRelationshipsTransactionsLinksWithDefaults() *AccountResourceRelationshipsTransactionsLinks {
	this := AccountResourceRelationshipsTransactionsLinks{}
	return &this
}

// GetRelated returns the Related field value
func (o *AccountResourceRelationshipsTransactionsLinks) GetRelated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Related
}

// GetRelatedOk returns a tuple with the Related field value
// and a boolean to check if the value has been set.
func (o *AccountResourceRelationshipsTransactionsLinks) GetRelatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Related, true
}

// SetRelated sets field value
func (o *AccountResourceRelationshipsTransactionsLinks) SetRelated(v string) {
	o.Related = v
}

func (o AccountResourceRelationshipsTransactionsLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["related"] = o.Related
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResourceRelationshipsTransactionsLinks struct {
	value *AccountResourceRelationshipsTransactionsLinks
	isSet bool
}

func (v NullableAccountResourceRelationshipsTransactionsLinks) Get() *AccountResourceRelationshipsTransactionsLinks {
	return v.value
}

func (v *NullableAccountResourceRelationshipsTransactionsLinks) Set(val *AccountResourceRelationshipsTransactionsLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResourceRelationshipsTransactionsLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResourceRelationshipsTransactionsLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResourceRelationshipsTransactionsLinks(val *AccountResourceRelationshipsTransactionsLinks) *NullableAccountResourceRelationshipsTransactionsLinks {
	return &NullableAccountResourceRelationshipsTransactionsLinks{value: val, isSet: true}
}

func (v NullableAccountResourceRelationshipsTransactionsLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResourceRelationshipsTransactionsLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


