/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It's new, it's exciting and it's just the beginning.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TransactionResourceRelationships struct for TransactionResourceRelationships
type TransactionResourceRelationships struct {
	Account        TransactionResourceRelationshipsAccount  `json:"account"`
	Tags           TransactionResourceRelationshipsTags     `json:"tags"`
	Category       TransactionResourceRelationshipsCategory `json:"category"`
	ParentCategory TransactionResourceRelationshipsCategory `json:"parentCategory"`
}

type CategoryData struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}

type TransactionResourceRelationshipsCategory struct {
	Data *CategoryData `json:"data"`
}
