/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// AccountResourceAttributes struct for AccountResourceAttributes
type AccountResourceAttributes struct {
	// The name associated with the account in the Up application.
	DisplayName string `json:"displayName"`
	// The bank account type of this account.
	AccountType AccountTypeEnum `json:"accountType"`
	// The ownership structure for this account.
	OwnershipType OwnershipTypeEnum `json:"ownershipType"`
	// The available balance of the account, taking into account any amounts that are currently on hold.
	Balance MoneyObject `json:"balance"`
	// The date-time at which this account was first opened.
	CreatedAt time.Time `json:"createdAt"`
}

// NewAccountResourceAttributes instantiates a new AccountResourceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResourceAttributes(displayName string, accountType AccountTypeEnum, ownershipType OwnershipTypeEnum, balance MoneyObject, createdAt time.Time) *AccountResourceAttributes {
	this := AccountResourceAttributes{}
	this.DisplayName = displayName
	this.AccountType = accountType
	this.OwnershipType = ownershipType
	this.Balance = balance
	this.CreatedAt = createdAt
	return &this
}

// NewAccountResourceAttributesWithDefaults instantiates a new AccountResourceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResourceAttributesWithDefaults() *AccountResourceAttributes {
	this := AccountResourceAttributes{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *AccountResourceAttributes) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributes) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AccountResourceAttributes) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetAccountType returns the AccountType field value
func (o *AccountResourceAttributes) GetAccountType() AccountTypeEnum {
	if o == nil {
		var ret AccountTypeEnum
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributes) GetAccountTypeOk() (*AccountTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *AccountResourceAttributes) SetAccountType(v AccountTypeEnum) {
	o.AccountType = v
}

// GetOwnershipType returns the OwnershipType field value
func (o *AccountResourceAttributes) GetOwnershipType() OwnershipTypeEnum {
	if o == nil {
		var ret OwnershipTypeEnum
		return ret
	}

	return o.OwnershipType
}

// GetOwnershipTypeOk returns a tuple with the OwnershipType field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributes) GetOwnershipTypeOk() (*OwnershipTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnershipType, true
}

// SetOwnershipType sets field value
func (o *AccountResourceAttributes) SetOwnershipType(v OwnershipTypeEnum) {
	o.OwnershipType = v
}

// GetBalance returns the Balance field value
func (o *AccountResourceAttributes) GetBalance() MoneyObject {
	if o == nil {
		var ret MoneyObject
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributes) GetBalanceOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *AccountResourceAttributes) SetBalance(v MoneyObject) {
	o.Balance = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountResourceAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountResourceAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o AccountResourceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["displayName"] = o.DisplayName
	}
	if true {
		toSerialize["accountType"] = o.AccountType
	}
	if true {
		toSerialize["ownershipType"] = o.OwnershipType
	}
	if true {
		toSerialize["balance"] = o.Balance
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResourceAttributes struct {
	value *AccountResourceAttributes
	isSet bool
}

func (v NullableAccountResourceAttributes) Get() *AccountResourceAttributes {
	return v.value
}

func (v *NullableAccountResourceAttributes) Set(val *AccountResourceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResourceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResourceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResourceAttributes(val *AccountResourceAttributes) *NullableAccountResourceAttributes {
	return &NullableAccountResourceAttributes{value: val, isSet: true}
}

func (v NullableAccountResourceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResourceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
