/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CategoryResource Provides information about a category and its ancestry. 
type CategoryResource struct {
	// The type of this resource: `categories`
	Type string `json:"type"`
	// The unique identifier for this category. This is a human-readable but URL-safe value. 
	Id string `json:"id"`
	Attributes CategoryResourceAttributes `json:"attributes"`
	Relationships CategoryResourceRelationships `json:"relationships"`
	Links AccountResourceLinks `json:"links,omitempty"`
}
