/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListAccountsResponseLinks struct for ListAccountsResponseLinks
type ListAccountsResponseLinks struct {
	// The link to the previous page in the results. If this value is `null` there is no previous page. 
	Prev NullableString `json:"prev"`
	// The link to the next page in the results. If this value is `null` there is no next page. 
	Next NullableString `json:"next"`
}

// NewListAccountsResponseLinks instantiates a new ListAccountsResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAccountsResponseLinks(prev NullableString, next NullableString) *ListAccountsResponseLinks {
	this := ListAccountsResponseLinks{}
	this.Prev = prev
	this.Next = next
	return &this
}

// NewListAccountsResponseLinksWithDefaults instantiates a new ListAccountsResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAccountsResponseLinksWithDefaults() *ListAccountsResponseLinks {
	this := ListAccountsResponseLinks{}
	return &this
}

// GetPrev returns the Prev field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListAccountsResponseLinks) GetPrev() string {
	if o == nil || o.Prev.Get() == nil {
		var ret string
		return ret
	}

	return *o.Prev.Get()
}

// GetPrevOk returns a tuple with the Prev field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAccountsResponseLinks) GetPrevOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Prev.Get(), o.Prev.IsSet()
}

// SetPrev sets field value
func (o *ListAccountsResponseLinks) SetPrev(v string) {
	o.Prev.Set(&v)
}

// GetNext returns the Next field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListAccountsResponseLinks) GetNext() string {
	if o == nil || o.Next.Get() == nil {
		var ret string
		return ret
	}

	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAccountsResponseLinks) GetNextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// SetNext sets field value
func (o *ListAccountsResponseLinks) SetNext(v string) {
	o.Next.Set(&v)
}

func (o ListAccountsResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["prev"] = o.Prev.Get()
	}
	if true {
		toSerialize["next"] = o.Next.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableListAccountsResponseLinks struct {
	value *ListAccountsResponseLinks
	isSet bool
}

func (v NullableListAccountsResponseLinks) Get() *ListAccountsResponseLinks {
	return v.value
}

func (v *NullableListAccountsResponseLinks) Set(val *ListAccountsResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListAccountsResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListAccountsResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAccountsResponseLinks(val *ListAccountsResponseLinks) *NullableListAccountsResponseLinks {
	return &NullableListAccountsResponseLinks{value: val, isSet: true}
}

func (v NullableListAccountsResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAccountsResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


