/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionResourceRelationshipsCategoryLinks struct for TransactionResourceRelationshipsCategoryLinks
type TransactionResourceRelationshipsCategoryLinks struct {
	// The link to retrieve or modify linkage between this resources and the related resource(s) in this relationship. 
	Self string `json:"self"`
	// The link to retrieve the related resource(s) in this relationship. 
	Related *string `json:"related,omitempty"`
}

// NewTransactionResourceRelationshipsCategoryLinks instantiates a new TransactionResourceRelationshipsCategoryLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceRelationshipsCategoryLinks(self string) *TransactionResourceRelationshipsCategoryLinks {
	this := TransactionResourceRelationshipsCategoryLinks{}
	this.Self = self
	return &this
}

// NewTransactionResourceRelationshipsCategoryLinksWithDefaults instantiates a new TransactionResourceRelationshipsCategoryLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceRelationshipsCategoryLinksWithDefaults() *TransactionResourceRelationshipsCategoryLinks {
	this := TransactionResourceRelationshipsCategoryLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *TransactionResourceRelationshipsCategoryLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceRelationshipsCategoryLinks) GetSelfOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *TransactionResourceRelationshipsCategoryLinks) SetSelf(v string) {
	o.Self = v
}

// GetRelated returns the Related field value if set, zero value otherwise.
func (o *TransactionResourceRelationshipsCategoryLinks) GetRelated() string {
	if o == nil || o.Related == nil {
		var ret string
		return ret
	}
	return *o.Related
}

// GetRelatedOk returns a tuple with the Related field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResourceRelationshipsCategoryLinks) GetRelatedOk() (*string, bool) {
	if o == nil || o.Related == nil {
		return nil, false
	}
	return o.Related, true
}

// HasRelated returns a boolean if a field has been set.
func (o *TransactionResourceRelationshipsCategoryLinks) HasRelated() bool {
	if o != nil && o.Related != nil {
		return true
	}

	return false
}

// SetRelated gets a reference to the given string and assigns it to the Related field.
func (o *TransactionResourceRelationshipsCategoryLinks) SetRelated(v string) {
	o.Related = &v
}

func (o TransactionResourceRelationshipsCategoryLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["self"] = o.Self
	}
	if o.Related != nil {
		toSerialize["related"] = o.Related
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionResourceRelationshipsCategoryLinks struct {
	value *TransactionResourceRelationshipsCategoryLinks
	isSet bool
}

func (v NullableTransactionResourceRelationshipsCategoryLinks) Get() *TransactionResourceRelationshipsCategoryLinks {
	return v.value
}

func (v *NullableTransactionResourceRelationshipsCategoryLinks) Set(val *TransactionResourceRelationshipsCategoryLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceRelationshipsCategoryLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceRelationshipsCategoryLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceRelationshipsCategoryLinks(val *TransactionResourceRelationshipsCategoryLinks) *NullableTransactionResourceRelationshipsCategoryLinks {
	return &NullableTransactionResourceRelationshipsCategoryLinks{value: val, isSet: true}
}

func (v NullableTransactionResourceRelationshipsCategoryLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceRelationshipsCategoryLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


