/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OwnershipTypeEnum Specifies the structure under which a bank account is owned. Currently returned values are `INDIVIDUAL` and `JOINT`. 
type OwnershipTypeEnum string

// List of OwnershipTypeEnum
const (
	INDIVIDUAL OwnershipTypeEnum = "INDIVIDUAL"
	JOINT OwnershipTypeEnum = "JOINT"
)

var allowedOwnershipTypeEnumEnumValues = []OwnershipTypeEnum{
	"INDIVIDUAL",
	"JOINT",
}

func (v *OwnershipTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OwnershipTypeEnum(value)
	for _, existing := range allowedOwnershipTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OwnershipTypeEnum", value)
}

// NewOwnershipTypeEnumFromValue returns a pointer to a valid OwnershipTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOwnershipTypeEnumFromValue(v string) (*OwnershipTypeEnum, error) {
	ev := OwnershipTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OwnershipTypeEnum: valid values are %v", v, allowedOwnershipTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OwnershipTypeEnum) IsValid() bool {
	for _, existing := range allowedOwnershipTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OwnershipTypeEnum value
func (v OwnershipTypeEnum) Ptr() *OwnershipTypeEnum {
	return &v
}

type NullableOwnershipTypeEnum struct {
	value *OwnershipTypeEnum
	isSet bool
}

func (v NullableOwnershipTypeEnum) Get() *OwnershipTypeEnum {
	return v.value
}

func (v *NullableOwnershipTypeEnum) Set(val *OwnershipTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnershipTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnershipTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnershipTypeEnum(val *OwnershipTypeEnum) *NullableOwnershipTypeEnum {
	return &NullableOwnershipTypeEnum{value: val, isSet: true}
}

func (v NullableOwnershipTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnershipTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

