/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListCategoriesResponse Successful response to get all categories and their ancestry. The returned list is not paginated. 
type ListCategoriesResponse struct {
	// The list of categories returned in this response. 
	Data []CategoryResource `json:"data"`
}

// NewListCategoriesResponse instantiates a new ListCategoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCategoriesResponse(data []CategoryResource) *ListCategoriesResponse {
	this := ListCategoriesResponse{}
	this.Data = data
	return &this
}

// NewListCategoriesResponseWithDefaults instantiates a new ListCategoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCategoriesResponseWithDefaults() *ListCategoriesResponse {
	this := ListCategoriesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListCategoriesResponse) GetData() []CategoryResource {
	if o == nil {
		var ret []CategoryResource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListCategoriesResponse) GetDataOk() ([]CategoryResource, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListCategoriesResponse) SetData(v []CategoryResource) {
	o.Data = v
}

func (o ListCategoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableListCategoriesResponse struct {
	value *ListCategoriesResponse
	isSet bool
}

func (v NullableListCategoriesResponse) Get() *ListCategoriesResponse {
	return v.value
}

func (v *NullableListCategoriesResponse) Set(val *ListCategoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCategoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCategoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCategoriesResponse(val *ListCategoriesResponse) *NullableListCategoriesResponse {
	return &NullableListCategoriesResponse{value: val, isSet: true}
}

func (v NullableListCategoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCategoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


