/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionResourceRelationshipsTagsData struct for TransactionResourceRelationshipsTagsData
type TransactionResourceRelationshipsTagsData struct {
	// The type of this resource: `tags`
	Type string `json:"type"`
	// The label of the tag, which also acts as the tag’s unique identifier. 
	Id string `json:"id"`
}

// NewTransactionResourceRelationshipsTagsData instantiates a new TransactionResourceRelationshipsTagsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceRelationshipsTagsData(type_ string, id string) *TransactionResourceRelationshipsTagsData {
	this := TransactionResourceRelationshipsTagsData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewTransactionResourceRelationshipsTagsDataWithDefaults instantiates a new TransactionResourceRelationshipsTagsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceRelationshipsTagsDataWithDefaults() *TransactionResourceRelationshipsTagsData {
	this := TransactionResourceRelationshipsTagsData{}
	return &this
}

// GetType returns the Type field value
func (o *TransactionResourceRelationshipsTagsData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceRelationshipsTagsData) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TransactionResourceRelationshipsTagsData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *TransactionResourceRelationshipsTagsData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceRelationshipsTagsData) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TransactionResourceRelationshipsTagsData) SetId(v string) {
	o.Id = v
}

func (o TransactionResourceRelationshipsTagsData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionResourceRelationshipsTagsData struct {
	value *TransactionResourceRelationshipsTagsData
	isSet bool
}

func (v NullableTransactionResourceRelationshipsTagsData) Get() *TransactionResourceRelationshipsTagsData {
	return v.value
}

func (v *NullableTransactionResourceRelationshipsTagsData) Set(val *TransactionResourceRelationshipsTagsData) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceRelationshipsTagsData) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceRelationshipsTagsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceRelationshipsTagsData(val *TransactionResourceRelationshipsTagsData) *NullableTransactionResourceRelationshipsTagsData {
	return &NullableTransactionResourceRelationshipsTagsData{value: val, isSet: true}
}

func (v NullableTransactionResourceRelationshipsTagsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceRelationshipsTagsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


