/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionResourceRelationshipsTagsLinks struct for TransactionResourceRelationshipsTagsLinks
type TransactionResourceRelationshipsTagsLinks struct {
	// The link to retrieve or modify linkage between this resources and the related resource(s) in this relationship. 
	Self string `json:"self"`
}

// NewTransactionResourceRelationshipsTagsLinks instantiates a new TransactionResourceRelationshipsTagsLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceRelationshipsTagsLinks(self string) *TransactionResourceRelationshipsTagsLinks {
	this := TransactionResourceRelationshipsTagsLinks{}
	this.Self = self
	return &this
}

// NewTransactionResourceRelationshipsTagsLinksWithDefaults instantiates a new TransactionResourceRelationshipsTagsLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceRelationshipsTagsLinksWithDefaults() *TransactionResourceRelationshipsTagsLinks {
	this := TransactionResourceRelationshipsTagsLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *TransactionResourceRelationshipsTagsLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceRelationshipsTagsLinks) GetSelfOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *TransactionResourceRelationshipsTagsLinks) SetSelf(v string) {
	o.Self = v
}

func (o TransactionResourceRelationshipsTagsLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["self"] = o.Self
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionResourceRelationshipsTagsLinks struct {
	value *TransactionResourceRelationshipsTagsLinks
	isSet bool
}

func (v NullableTransactionResourceRelationshipsTagsLinks) Get() *TransactionResourceRelationshipsTagsLinks {
	return v.value
}

func (v *NullableTransactionResourceRelationshipsTagsLinks) Set(val *TransactionResourceRelationshipsTagsLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceRelationshipsTagsLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceRelationshipsTagsLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceRelationshipsTagsLinks(val *TransactionResourceRelationshipsTagsLinks) *NullableTransactionResourceRelationshipsTagsLinks {
	return &NullableTransactionResourceRelationshipsTagsLinks{value: val, isSet: true}
}

func (v NullableTransactionResourceRelationshipsTagsLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceRelationshipsTagsLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


