/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WebhookDeliveryLogResourceAttributesRequest Information about the request that was sent to the webhook URL. 
type WebhookDeliveryLogResourceAttributesRequest struct {
	// The payload that was sent in the request body. 
	Body string `json:"body"`
}

// NewWebhookDeliveryLogResourceAttributesRequest instantiates a new WebhookDeliveryLogResourceAttributesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryLogResourceAttributesRequest(body string) *WebhookDeliveryLogResourceAttributesRequest {
	this := WebhookDeliveryLogResourceAttributesRequest{}
	this.Body = body
	return &this
}

// NewWebhookDeliveryLogResourceAttributesRequestWithDefaults instantiates a new WebhookDeliveryLogResourceAttributesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryLogResourceAttributesRequestWithDefaults() *WebhookDeliveryLogResourceAttributesRequest {
	this := WebhookDeliveryLogResourceAttributesRequest{}
	return &this
}

// GetBody returns the Body field value
func (o *WebhookDeliveryLogResourceAttributesRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogResourceAttributesRequest) GetBodyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *WebhookDeliveryLogResourceAttributesRequest) SetBody(v string) {
	o.Body = v
}

func (o WebhookDeliveryLogResourceAttributesRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["body"] = o.Body
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookDeliveryLogResourceAttributesRequest struct {
	value *WebhookDeliveryLogResourceAttributesRequest
	isSet bool
}

func (v NullableWebhookDeliveryLogResourceAttributesRequest) Get() *WebhookDeliveryLogResourceAttributesRequest {
	return v.value
}

func (v *NullableWebhookDeliveryLogResourceAttributesRequest) Set(val *WebhookDeliveryLogResourceAttributesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryLogResourceAttributesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryLogResourceAttributesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryLogResourceAttributesRequest(val *WebhookDeliveryLogResourceAttributesRequest) *NullableWebhookDeliveryLogResourceAttributesRequest {
	return &NullableWebhookDeliveryLogResourceAttributesRequest{value: val, isSet: true}
}

func (v NullableWebhookDeliveryLogResourceAttributesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryLogResourceAttributesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


