/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WebhookDeliveryLogResourceRelationships struct for WebhookDeliveryLogResourceRelationships
type WebhookDeliveryLogResourceRelationships struct {
	WebhookEvent WebhookDeliveryLogResourceRelationshipsWebhookEvent `json:"webhookEvent"`
}

// NewWebhookDeliveryLogResourceRelationships instantiates a new WebhookDeliveryLogResourceRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryLogResourceRelationships(webhookEvent WebhookDeliveryLogResourceRelationshipsWebhookEvent) *WebhookDeliveryLogResourceRelationships {
	this := WebhookDeliveryLogResourceRelationships{}
	this.WebhookEvent = webhookEvent
	return &this
}

// NewWebhookDeliveryLogResourceRelationshipsWithDefaults instantiates a new WebhookDeliveryLogResourceRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryLogResourceRelationshipsWithDefaults() *WebhookDeliveryLogResourceRelationships {
	this := WebhookDeliveryLogResourceRelationships{}
	return &this
}

// GetWebhookEvent returns the WebhookEvent field value
func (o *WebhookDeliveryLogResourceRelationships) GetWebhookEvent() WebhookDeliveryLogResourceRelationshipsWebhookEvent {
	if o == nil {
		var ret WebhookDeliveryLogResourceRelationshipsWebhookEvent
		return ret
	}

	return o.WebhookEvent
}

// GetWebhookEventOk returns a tuple with the WebhookEvent field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogResourceRelationships) GetWebhookEventOk() (*WebhookDeliveryLogResourceRelationshipsWebhookEvent, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WebhookEvent, true
}

// SetWebhookEvent sets field value
func (o *WebhookDeliveryLogResourceRelationships) SetWebhookEvent(v WebhookDeliveryLogResourceRelationshipsWebhookEvent) {
	o.WebhookEvent = v
}

func (o WebhookDeliveryLogResourceRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["webhookEvent"] = o.WebhookEvent
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookDeliveryLogResourceRelationships struct {
	value *WebhookDeliveryLogResourceRelationships
	isSet bool
}

func (v NullableWebhookDeliveryLogResourceRelationships) Get() *WebhookDeliveryLogResourceRelationships {
	return v.value
}

func (v *NullableWebhookDeliveryLogResourceRelationships) Set(val *WebhookDeliveryLogResourceRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryLogResourceRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryLogResourceRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryLogResourceRelationships(val *WebhookDeliveryLogResourceRelationships) *NullableWebhookDeliveryLogResourceRelationships {
	return &NullableWebhookDeliveryLogResourceRelationships{value: val, isSet: true}
}

func (v NullableWebhookDeliveryLogResourceRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryLogResourceRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


