/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WebhookInputResourceAttributes struct for WebhookInputResourceAttributes
type WebhookInputResourceAttributes struct {
	// The URL that this webhook should post events to. This must be a valid HTTP or HTTPS URL that does not exceed 300 characters in length. 
	Url string `json:"url"`
	// An optional description for this webhook, up to 64 characters in length. 
	Description NullableString `json:"description,omitempty"`
}

// NewWebhookInputResourceAttributes instantiates a new WebhookInputResourceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookInputResourceAttributes(url string) *WebhookInputResourceAttributes {
	this := WebhookInputResourceAttributes{}
	this.Url = url
	return &this
}

// NewWebhookInputResourceAttributesWithDefaults instantiates a new WebhookInputResourceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookInputResourceAttributesWithDefaults() *WebhookInputResourceAttributes {
	this := WebhookInputResourceAttributes{}
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookInputResourceAttributes) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookInputResourceAttributes) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookInputResourceAttributes) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookInputResourceAttributes) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookInputResourceAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookInputResourceAttributes) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *WebhookInputResourceAttributes) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WebhookInputResourceAttributes) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WebhookInputResourceAttributes) UnsetDescription() {
	o.Description.Unset()
}

func (o WebhookInputResourceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookInputResourceAttributes struct {
	value *WebhookInputResourceAttributes
	isSet bool
}

func (v NullableWebhookInputResourceAttributes) Get() *WebhookInputResourceAttributes {
	return v.value
}

func (v *NullableWebhookInputResourceAttributes) Set(val *WebhookInputResourceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookInputResourceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookInputResourceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookInputResourceAttributes(val *WebhookInputResourceAttributes) *NullableWebhookInputResourceAttributes {
	return &NullableWebhookInputResourceAttributes{value: val, isSet: true}
}

func (v NullableWebhookInputResourceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookInputResourceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


