/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListWebhookDeliveryLogsResponse Successful response to get all delivery logs for a webhook. This returns a paginated list of delivery logs, which can be scrolled by following the `next` and `prev` links if present. 
type ListWebhookDeliveryLogsResponse struct {
	// The list of delivery logs returned in this response. 
	Data []WebhookDeliveryLogResource `json:"data"`
	Links ListAccountsResponseLinks `json:"links"`
}

// NewListWebhookDeliveryLogsResponse instantiates a new ListWebhookDeliveryLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWebhookDeliveryLogsResponse(data []WebhookDeliveryLogResource, links ListAccountsResponseLinks) *ListWebhookDeliveryLogsResponse {
	this := ListWebhookDeliveryLogsResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewListWebhookDeliveryLogsResponseWithDefaults instantiates a new ListWebhookDeliveryLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWebhookDeliveryLogsResponseWithDefaults() *ListWebhookDeliveryLogsResponse {
	this := ListWebhookDeliveryLogsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListWebhookDeliveryLogsResponse) GetData() []WebhookDeliveryLogResource {
	if o == nil {
		var ret []WebhookDeliveryLogResource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListWebhookDeliveryLogsResponse) GetDataOk() (*[]WebhookDeliveryLogResource, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListWebhookDeliveryLogsResponse) SetData(v []WebhookDeliveryLogResource) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *ListWebhookDeliveryLogsResponse) GetLinks() ListAccountsResponseLinks {
	if o == nil {
		var ret ListAccountsResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListWebhookDeliveryLogsResponse) GetLinksOk() (*ListAccountsResponseLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListWebhookDeliveryLogsResponse) SetLinks(v ListAccountsResponseLinks) {
	o.Links = v
}

func (o ListWebhookDeliveryLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableListWebhookDeliveryLogsResponse struct {
	value *ListWebhookDeliveryLogsResponse
	isSet bool
}

func (v NullableListWebhookDeliveryLogsResponse) Get() *ListWebhookDeliveryLogsResponse {
	return v.value
}

func (v *NullableListWebhookDeliveryLogsResponse) Set(val *ListWebhookDeliveryLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListWebhookDeliveryLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListWebhookDeliveryLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWebhookDeliveryLogsResponse(val *ListWebhookDeliveryLogsResponse) *NullableListWebhookDeliveryLogsResponse {
	return &NullableListWebhookDeliveryLogsResponse{value: val, isSet: true}
}

func (v NullableListWebhookDeliveryLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWebhookDeliveryLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


